services:
  postgres_app:
    image: postgres:18-alpine
    container_name: waitery-postgres-app
    restart: unless-stopped
    environment:
      POSTGRES_USER: waitery
      POSTGRES_PASSWORD: waitery
      POSTGRES_DB: waitery_app
    ports:
      - '5432:5432'
    volumes:
      - postgres_app_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U waitery -d waitery_app']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_app_data:
