export const IUSER_CONTRACT = 'IUSER_CONTRACT';
export const COMPARE_HASH = 'COMPARE_HASH';
export const IORGANIZATION_CONTRACT = 'IORGANIZATION_CONTRACT';
export const IAUTH_CONTRACT = 'IAUTH_CONTRACT';
export const IINGREDIENT_CONTRACT = 'IINGREDIENT_CONTRACT';
export const ICATEGORY_CONTRACT = 'ICATEGORY_CONTRACT';
